[package]
name = "examples_orders"
version = "0.1.0"
edition = "2024"

[dependencies]
ig-client = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }