services:
  postgres:
    image: postgres:16
    container_name: ig_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AS09.1qa
      POSTGRES_DB: ig
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    name: postgres_volume

networks:
  postgres_network:
    name: postgres_net