[package]
name = "examples_chart"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "chart_lightstreamer"
path = "src/bin/chart_lightstreamer.rs"

[dependencies]
ig-client = { workspace = true }
lightstreamer-rs = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }