[package]
name = "rate_limiter"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
futures = { workspace = true }
ig-client = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
